### ISSUE TITLE
Why do you replicate inp for sequence length times at dim 2?

### ISSUE THREAD

**Issue by DNALuo** [ywchao/image-play#1]
Hi Yuwei,

I am re-implementing your 2D pose forecasting work for now. But I am confused by the part in lib/models/hg-256-res-clstm.lua. Why do you replicate inp for sequence length times at dim 2? If you want to get the residual of the encoder output, will using the input copy work as the same?

**Comment by ywchao** [comment]
![github_illustration1](https://user-images.githubusercontent.com/1518599/51791290-98bd7280-2155-11e9-88d5-379782f795c3.png)

The figure above hopefully can help explain this better. Note that the encode output is reused at every timestep, since the LSTMs here only provide the residuals. Besides, the LSTM module we used returns all the output in one tensor, which has the 2nd dimension as the temporal dimension. Therefore we replicate the encoder output sequence length times (i.e. 16x) in the 2nd dimension and add to the LSTM output.

**Comment by DNALuo** [comment]
> ![github_illustration1](https://user-images.githubusercontent.com/1518599/51791290-98bd7280-2155-11e9-88d5-379782f795c3.png)
> 
> The figure above hopefully can help explain this better. Note that the encode output is reused at every timestep, since the LSTMs here only provide the residuals. Besides, the LSTM module we used returns all the output in one tensor, which has the 2nd dimension as the temporal dimension. Therefore we replicate the encoder output sequence length times (i.e. 16x) in the 2nd dimension and add to the LSTM output.

Thanks for the reply! That picture helps a lot!
